### ISSUE TITLE
gedit 45 (flatpak) not using/finding locally defined languages.

### ISSUE THREAD

**Issue by splace** [gedit-technology/libgedit-gtksourceview#4]
`~/.local/share/gtksourceview-4/language-specs`

**Comment by rui-nibau** [comment]
Hello.

You need to put your files in ~/.local/share/libgedit-gtksourceview-300/language-specs

See https://gedit-technology.net/developer-docs/libgedit-gtksourceview-300/porting-guide-gtksourceview-4-to-libgedit-gtksourceview-300.html

**Comment by splace** [comment]
why not use the same location? or a symlink?
