### ISSUE TITLE
language spec file fails to load

### ISSUE THREAD

**Issue by MeisterP** [gedit-technology/libgedit-gtksourceview#5]
The file used to work with gtksourceview but fails with libgedit-gtksourceview

`Failed to load '/home/poncho/.local/share/libgedit-gtksourceview-300/language-specs/gentoo.lang': invalid context reference “sh:let-command”`

Attached the gentoo.lang file:
[gentoo.lang.txt](https://github.com/gedit-technology/libgedit-gtksourceview/files/12504731/gentoo.lang.txt)

**Comment by swilmet** [comment]
It seems that gentoo.lang is not self-contained and depends on sh.lang (if I understand correctly).

So you need to copy sh.lang from GNOME's GtkSourceView, or adapt gentoo.lang.

**Comment by swilmet** [comment]
I close this issue because gentoo.lang is a third-party lang file, not part of the project.
